### ISSUE TITLE
Boolean vs Timestamp

### ISSUE THREAD

**Issue by vercotux** [yii2tech/ar-softdelete#1]
Would it not make sense to use a unix timestamp to indicate deletion as opposed to a simple boolean?

It is certainly important to know when a record was deleted, not just whether it was. It could both be done with one column by storing unix timestamps instead of booleans. A set value means that the record was deleted AND it also tells you when. The column being NULL means the record has not been deleted. Furthermore this could be done consistently with TimestampBehavior by calling the attribute "_deleted_at_".

The only (and perhaps negligible) downside is the possibility of slightly higher storage requirement (using INT instead of BIT).

At the very least this could be a configurable option of SoftDelete.

**Comment by klimov-paul** [comment]
You mau achieve this using `yii\db\Expression` in `softDeleteAttributeValues`:

```
'softDeleteAttributeValues' => [
    'deletedAt' => new Expression('NOW()')
],
```

**Comment by vercotux** [comment]
Would make sense to be the default, but I'm glad there's a simple way to do it. Thanks.

**Comment by klimov-paul** [comment]
d62def6057c4b1b3cd3ff464b2fba347666191d6

**Comment by vercotux** [comment]
Since you are at it, could you call it "_deleted_at_" instead of _deletedAt_, to make it more consistent with Yii2's TimestampBehavior defaults for [$createdAtAttribute](http://www.yiiframework.com/doc-2.0/yii-behaviors-timestampbehavior.html#$createdAtAttribute-detail) and [$updatedAtAttribute](http://www.yiiframework.com/doc-2.0/yii-behaviors-timestampbehavior.html#$updatedAtAttribute-detail) so that we end up with three:
- created_at
- updated_at
- deleted_at
