### ISSUE TITLE
composer.json problem

### ISSUE THREAD

**Issue by sheillendra** [yii2tech/ar-softdelete#10]
I get a problem when I want to update yii2 version to 2.0.14.1 hotfix version

Problem 1
    - The requested package yiisoft/yii2 2.0.14.1 exists as yiisoft/yii2[2.0.0,                                                                                         2.0.0-alpha, 2.0.0-beta, 2.0.0-rc, 2.0.1, 2.0.10, 2.0.11, 2.0.11.1, 2.0.11.2, 2.                                                                                        0.12, 2.0.13, 2.0.13.1, 2.0.14, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8,                                                                                         2.0.9, 2.1.x-dev, dev-master, 2.0.x-dev] but these are rejected by your constra                                                                                        int.
  Problem 2
    - yii2tech/ar-softdelete 1.0.1 requires yiisoft/yii2 * -> satisfiable by yii                                                                                        soft/yii2[2.0.0, 2.0.0-alpha, 2.0.0-beta, 2.0.0-rc, 2.0.1, 2.0.10, 2.0.11, 2.0.1                                                                                        1.1, 2.0.11.2, 2.0.12, 2.0.13, 2.0.13.1, 2.0.14, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0                                                                                        .6, 2.0.7, 2.0.8, 2.0.9, 2.1.x-dev, dev-master, 2.0.x-dev] but these conflict wi                                                                                        th your requirements or minimum-stability.
    - yii2tech/ar-softdelete 1.0.1 requires yiisoft/yii2 * -> satisfiable by yii                                                                                        soft/yii2[2.0.0, 2.0.0-alpha, 2.0.0-beta, 2.0.0-rc, 2.0.1, 2.0.10, 2.0.11, 2.0.1                                                                                        1.1, 2.0.11.2, 2.0.12, 2.0.13, 2.0.13.1, 2.0.14, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0                                                                                        .6, 2.0.7, 2.0.8, 2.0.9, 2.1.x-dev, dev-master, 2.0.x-dev] but these conflict wi                                                                                        th your requirements or minimum-stability.
    - Installation request for yii2tech/ar-softdelete ^1.0.1 -> satisfiable by y                                                                                        ii2tech/ar-softdelete[1.0.1].

**Comment by klimov-paul** [comment]
See https://github.com/yiisoft/yii2/issues/15771
