### ISSUE TITLE
Failed to delete the object for unknown reason.

### ISSUE THREAD

**Issue by akoch-ov** [yii2tech/ar-softdelete#11]
https://github.com/yii2tech/ar-softdelete/blob/9a5a741a797711b7e0c1146bffe14e015d278629/src/SoftDeleteBehavior.php#L185

updateAttributes() return int the number of rows affected, but DeleteAction expects bool.
https://github.com/yiisoft/yii2/blob/4f80cda7130da5259ce93fe41eb681cbb70f30be/framework/rest/DeleteAction.php#L36

**Comment by klimov-paul** [comment]
This is matching original `ActiveRecord::delete()` method as it returns number of affected rows:
https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L869

Can't see any trouble here.

**Comment by akoch-ov** [comment]
Ok, you are right.
Maybe this place wrong?
https://github.com/yii2tech/ar-softdelete/blob/9a5a741a797711b7e0c1146bffe14e015d278629/src/SoftDeleteBehavior.php#L391
If replace it with "$event->handled = true;" it will be ok!
