### ISSUE TITLE
Exception: Failed to delete the object for unknown reason.

### ISSUE THREAD

**Issue by akoch-ov** [yii2tech/ar-softdelete#12]
Hello! DeleteAction expects not false if deletion successful.
https://github.com/yiisoft/yii2/blob/4f80cda7130da5259ce93fe41eb681cbb70f30be/framework/rest/DeleteAction.php#L36

Maybe this line is wrong?
https://github.com/yii2tech/ar-softdelete/blob/9a5a741a797711b7e0c1146bffe14e015d278629/src/SoftDeleteBehavior.php#L391
If replace it with "$event->handled = true;" it will be ok!

**Comment by klimov-paul** [comment]
No, code is correct: it cancels deletion of the record, thus `delete()` obviously returns `false`.
Yii does not provide any way to influence result of `ActiveRecord::delete()` method via event handler.

**Comment by akoch-ov** [comment]
Then, is it bug in Yii?

**Comment by akoch-ov** [comment]
Извиняюсь, что по-русски...
А нет возможности сделать какую-нить настройку чтоб использовалось $event->handled = true; ?
В этом случае всё нормально срабатывает...
