### ISSUE TITLE
suggestion for query deleted

### ISSUE THREAD

**Issue by budimm** [yii2tech/ar-softdelete#21]
### What steps will reproduce the problem?
model :
```
    /**
     * @return \yii\db\ActiveQuery|SoftDeleteQueryBehavior
     */
    public static function find(){
        // $query = parent::find();
        $query->attachBehavior('softDelete', SoftDeleteQueryBehavior::className());
        return $query;
    }
```

controller :
```
        $query = TappsPrincipalHolding::find()
             ->notDeleted()->one();
```

### What is the expected result?
iam has alot of query for it, so how if remove `notDeleted` in controller, better if not used it. Cz i'll not need it in App, just need in database if really needed..

### suggestion :
`        $query = parent::find()->andWhere(['=', 'isDeleted', 0]);
`

is it right ?
or it should works without my changes ?
Thanks for pay attention..

**Comment by klimov-paul** [comment]
Sorry, but I can not make any sense from the words you have written here.
Try to seek help elsewhere.
