### ISSUE TITLE
alias problem.

### ISSUE THREAD

**Issue by rezaei121** [yii2tech/ar-softdelete#22]
hi. i am test sample find:
`Contacts::find()
->alias('c')
 ->joinWith(['sexuality' => function (\yii\db\ActiveQuery $query) {
 $query->alias('s');
}])->createCommand()->getSql();`
query result: 
`SELECT
    "c".*
FROM
    "contacts" "c"
LEFT JOIN
    "domain" "s"
ON
    ("c"."sexuality_id" = "s"."id") AND("domain"."deleted_at" IS NULL)
WHERE
    "contacts"."deleted_at" IS NULL
`
alias does not apply in query.

**Comment by rezaei121** [comment]
Another example that has errors:
`Contacts::find()
            ->alias('c')
            ->all();`
query result: 
`SELECT * FROM "contacts" "c" WHERE "contacts"."deleted_at" IS NULL`

**Comment by klimov-paul** [comment]
Duplicates #19

**Comment by rezaei121** [comment]
I had seen it. at unit test use "deleted" method.
but me rewrite "find" method:
`
    public static function find()
    {
        $query = Yii::createObject(\common\components\db\ActiveQuery::className(), [get_called_class()]);
        $query->attachBehavior('softDelete', [
            'class' => SoftDeleteQueryBehavior::className(),
            'deletedCondition' => ['!=', 'deleted_at', null],
            'notDeletedCondition' => [
                'deleted_at' => null,
            ],
        ]);
        return $query->notDeleted();
    }
`
and run:
`Contacts::find() ->alias('c') ->all();`

find(with "notDeleted") Run Before alias, and table alias in query not apply.

**Comment by phrakon** [comment]
I found the similar issue used to joinWith method like below code

```
 $productQuery->joinWith([
"productValues.paramItemValue {$alias2}" => function (ParamItemValueQuery $query) {
                            $query->onCondition(null);
                            $q = clone $query;
                            $query->onCondition($q->getNotDeletedCondition());
                        },
                    ], false);
```

it refers to query object inside the top callback function:

```
app\models\shop\ParamItemValueQuery#1
(
   ...
    [on] => [
        0 => '<'
        1 => 'param_item_value.deleted_at'
        2 => 1
    ]
...
    [from] => [
        'param_item_value_5d7b60d20c343' => 'param_item_value'
    ]
...
    [yii\base\Component:_behaviors] => [
        'softDelete' => yii2tech\ar\softdelete\SoftDeleteQueryBehavior#2
        (
            [yii2tech\ar\softdelete\SoftDeleteQueryBehavior:_deletedCondition] => [
                0 => '>'
                1 => 'param_item_value.deleted_at'
                2 => 0
            ]
            [yii2tech\ar\softdelete\SoftDeleteQueryBehavior:_notDeletedCondition] => [
                0 => '<'
                1 => 'param_item_value.deleted_at'
                2 => 1
            ]
            [owner] => app\models\shop\ParamItemValueQuery#1(...)
            [yii\base\Behavior:_attachedEvents] => []
        )
    ]
   ...
)
```

because softdeletequery don't know about alias. i would compelled drop broken condition, create clone of original query (it clears private _behaviors property and drops behavior which has broken condition, but has correct alias; so after ensureBehaviors it would know about alias) and apply new condition. I know, we call it "govnokod", but i have no idea to fix it another way
