### ISSUE TITLE
Error using soft delete - Unknown Property 

### ISSUE THREAD

**Issue by lucasemanuel** [yii2tech/ar-softdelete#23]
**Unknown Property – yii\base\UnknownPropertyException**
Setting unknown property: app\models\Employee::isDeleted

To use soft delete should i insert the `isDeleted` attribute into the database employee table?

**Comment by klimov-paul** [comment]
https://github.com/yii2tech/ar-softdelete/blob/master/src/SoftDeleteBehavior.php#L84-L106

**Comment by lucasemanuel** [comment]
> **Unknown Property – yii\base\UnknownPropertyException**
> Setting unknown property: app\models\Employee::isDeleted
> 
> To use soft delete should i insert the `isDeleted` attribute into the database employee table?

Solted. There must be some attribute in the model to store the softdelete flag.
