### ISSUE TITLE
Soft Delete All not given 

### ISSUE THREAD

**Issue by indranshastri** [yii2tech/ar-softdelete#24]
I have inserted the behaviour in the active model now i need for soft delete all based on certain condition I cannot as there is no option for that 

Want some kind of function like SoftDeleteAll("condition") which will be same as delete all 

I had to wirite an update all like where i set all isdelete flag as 1 
I had to use it in  a relational model

**Comment by klimov-paul** [comment]
Static soft deleting for the batch records can not be implemented.
Such features as [smart deletion](https://github.com/yii2tech/ar-softdelete#smart-deletion-) or dynamic calculation of `softDeleteAttributeValues` would be broken in such way.

You can use `ActiveQuery::batch()` or `ActiveQuery::each()` to iterate over records, invoking soft delete per each:

```php
// using `ActiveQuery::batch()`:
foreach (Item::find()->batch() as $rows) {
    foreach ($rows as $row) {
        $row->softDelete();
    }
}

// using `ActiveQuery::each()`:
foreach (Item::find()->each() as $row) {
    $row->softDelete();
}
```
