### ISSUE TITLE
beforeSoftDelete() is wrongly documented

### ISSUE THREAD

**Issue by neverabe** [yii2tech/ar-softdelete#3]
This code wont work, because the method softDeleteInternal() will rewrite the values of the attributes during the execution of lines https://github.com/yii2tech/ar-softdelete/blob/master/SoftDeleteBehavior.php#L179-L185 which will only update the attributes defined in the `softDeleteAttributeValues` property using the values defined there.

``` php
   public function beforeSoftDelete()
    {
        $this->deletedAt = time(); // log the deletion date
        return true;
    }
```

Is the documented example which doesn't work.

**Comment by klimov-paul** [comment]
It would not work only if you rely on `deletedAt` as soft-delete attribute.
If you use status or flag change as it is provided in the docs - everything will be fine.
