### ISSUE TITLE
replaceRegularDelete not work when AR transactions enable

### ISSUE THREAD

**Issue by KoJIT2009** [yii2tech/ar-softdelete#6]
When AR transactions on scenario have OP_ALL or OP_DELETE, event return false and transaction rollback.

**Comment by klimov-paul** [comment]
There is no way to fix this: event should return `false` - otherwise the record deleting will be performed, but `false` result will also trigger transaction rollback.

**Comment by KoJIT2009** [comment]
Yes it is. It would be nice to add about this in the readme, because this is not an obvious behavior until you get into the source

**Comment by klimov-paul** [comment]
If you have a good wording - open a pull request for it.

**Comment by davidjeddy** [comment]
+1 for the mutated ->delete() to return true if successfully 'soft deleted'.
