### ISSUE TITLE
$model->delete() returns false when replaceRegularDelete => true

### ISSUE THREAD

**Issue by fh-jashmore** [yii2tech/ar-softdelete#7]
I know you have to stop a hard delete in the beforeDelete event. Which eventually returns false to the delete() function. Is there a proper way to get the delete function to not return false?
```
public function behaviors()
{
    return [
        'softDeleteBehavior' => [
            'class' => SoftDeleteBehavior::className(),
            'softDeleteAttributeValues' => [
                'whenDeleted' => new Expression('NOW()')
            ],
            'restoreAttributeValues' => [
                'whenDeleted' => null
            ],
            'replaceRegularDelete' => true
        ],
    ];
}
```

What I have so far was override the deleteAll static function in the model so that the ActiveRecord deleteInternal function would not hard delete the record
```
public static function deleteAll($condition = '', $params = [])
{
    return 1;
}
```

And remove the `$event->isValid = false;` line in the beforeDelete event function from SoftDeleteBehavior so that `$model->delete()` would eventually return true
```
public function beforeDelete($event)
{
    if (!$this->isDeleteAllowed()) {
        $this->softDeleteInternal();
//      $event->isValid = false;
    }
}
```

**Comment by klimov-paul** [comment]
Duplicates #6

**Comment by ezsky** [comment]
Why do not resolve and release new version?
