### ISSUE TITLE
Enhancements, questions

### ISSUE THREAD

**Issue by bobahvas** [yii2tech/ar-softdelete#8]
1. Существует ли возможность заставить редакторы видеть новые методы? (Конкретно PHPStorm)
1. Можно ли добавить метод isDeleted(), который будет возвращать реальный статус, в зависимости от логики при инициализации? В текущей реализации необходимо каждый раз прописывать логику (например $item->isDeleted === null ? do_something : do_another).
1. Чаще всего, когда применяется этот behavior, то нужно фильтровать данные таким образом, чтобы исключить удаленные записи из выборки. Можно ли автоматически добавлять условие в `find()` на фильтрацию? Только тут нельзя забывать про возможность добавления
```
    public static function find()
    {
        return new ItemQuery(get_called_class());
    }
```
При этом остается необходимость выборки удаленных записей. В этом плане есть хорошие реализации у Laravel, RoR, Sequelize (nodejs).
1. Может ли этот behavior стать частью ядра Yii? Это решило бы некоторые проблемы, описанные выше.

**Comment by klimov-paul** [comment]
> Существует ли возможность заставить редакторы видеть новые методы? (Конкретно PHPStorm)

С помощью PHPDoc:

```php
/* @var $model Item|\yii2tech\ar\softdelete\SoftDeleteBehavior */
$model = Item::findOne($id);

// or :

class ItemQuery extends ActiveQuery
{
    /**
     * @inheritdoc
     * @return Item[]|\yii2tech\ar\softdelete\SoftDeleteBehavior[]|array
     */
    public function all($db = null)
    {
        return parent::all($db);
    }

    /**
     * @inheritdoc
     * @return Item|\yii2tech\ar\softdelete\SoftDeleteBehavior|array|null
     */
    public function one($db = null)
    {
        return parent::one($db);
    }
}
```

> Можно ли добавить метод isDeleted(), который будет возвращать реальный статус, в зависимости от логики при инициализации?

Маловероятно, т.к. `$softDeleteAttributeValues` поддерживает различные варианты, в том числе `Closure`:
https://github.com/yii2tech/ar-softdelete/blob/master/SoftDeleteBehavior.php#L81
Кроме того, если вы отмечаете удаленные записи через булевый атрибут, например `$isDeleted`, то такой метод вам не нужен вовсе.
Впрочем, если у вас есть конкретное предложение по реализации - открывайте PR.

> Чаще всего, когда применяется этот behavior, то нужно фильтровать данные таким образом, чтобы исключить удаленные записи из выборки. Можно ли автоматически добавлять условие в find() на фильтрацию? Только тут нельзя забывать про возможность добавления

"Чаще всего" - это не "всегда".
Вы можете использовать механизм defaukt scope для этого если хотите:

```php
class ItemQuery extends ActiveQuery
{
    public static function find()
    {
        return parent::find()->andWhere(['isDeleted' => false]);
    }
}
```

Но тогда, вам придется сбрасывать это условие для выборки всех записей.
Лучше объявить scope метод `whereNotDeleted()`  и использовать его явно.

> Может ли этот behavior стать частью ядра Yii?

Это вопрос не ко мне, команда официально закрыла задачу по встроенным поведениям, отказавшись от реализации:
https://github.com/yiisoft/yii2/issues/2484
